var ownerSubmissionModal = '<div class="modal fade" id="ownerSubmissionModal" tabindex="-1" role="dialog" aria-labelledby="ownerSubmissionModal" aria-hidden="true">'
ownerSubmissionModal += '<div class="modal-dialog" role="document">'
ownerSubmissionModal += '<div class="modal-content">'
ownerSubmissionModal += '<div class="modal-header">'
ownerSubmissionModal += '<h5 class="modal-title" id="exampleModalLabel"><strong>Add a New Owner</strong></h5>'
ownerSubmissionModal += '<button type="button" class="close" data-dismiss="modal" aria-label="Close">'
ownerSubmissionModal += '<span aria-hidden="true">&times;</span>'
ownerSubmissionModal += '</button>'
ownerSubmissionModal += '</div>'
ownerSubmissionModal += '<div class="modal-body">'
ownerSubmissionModal += '<form method="post" id="createOwnerForm">'
ownerSubmissionModal += '<div class="form-row">'
ownerSubmissionModal += '<div class="form-group col-md-6">'
ownerSubmissionModal += '<label for="firstName">First Name</label>'
ownerSubmissionModal += '<input name="fname" type="text" class="form-control" id="firstName" placeholder="Enter First Name">'
ownerSubmissionModal += '</div>'
ownerSubmissionModal += '<div class="form-group col-md-6">'
ownerSubmissionModal += '<label for="lastName">Last Name</label>'
ownerSubmissionModal += '<input name="lname" type="text" class="form-control" id="lastName" placeholder="Enter Last Name">'
ownerSubmissionModal += '</div>'
ownerSubmissionModal += '</div>'
ownerSubmissionModal += '<div class="form-group">'            
ownerSubmissionModal += '<label for="addressOne">Address Line 1</label>'            
ownerSubmissionModal += '<input name="street1" type="text" class="form-control" id="adressOne" placeholder="Enter First Address Line">'            
ownerSubmissionModal += '</div>'            
ownerSubmissionModal += '<div class="form-group">'            
ownerSubmissionModal += '<label for="addressTwo">Address Line 2</label>'            
ownerSubmissionModal += '<input name="street2" type="text" class="form-control" id="addressTwo" placeholder="Enter Second Address Line">'            
ownerSubmissionModal += '</div>'            
ownerSubmissionModal += '<div class="form-row">'            
ownerSubmissionModal += '<div class="form-group col-md-6">'            
ownerSubmissionModal += '<label for="city">City</label>'            
ownerSubmissionModal += '<input name="city" type="text" class="form-control" id="city" placeholder="City">'            
ownerSubmissionModal += '</div>'            
ownerSubmissionModal += '<div class="form-group col-md-4">'            
ownerSubmissionModal += '<label for="state">State</label>'            
ownerSubmissionModal += '<select name="state" class="form-control" id="state">'            
ownerSubmissionModal += '<option value="AL">Alabama</option>'            
ownerSubmissionModal += '<option value="AK">Alaska</option>'            
ownerSubmissionModal += '<option value="AZ">Arizona</option>'            
ownerSubmissionModal += '<option value="AR">Arkansas</option>'            
ownerSubmissionModal += '<option value="CA">California</option>'            
ownerSubmissionModal += '<option value="CO">Colorado</option>'            
ownerSubmissionModal += '<option value="CT">Connecticut</option>'            
ownerSubmissionModal += '<option value="DE">Delaware</option>'            
ownerSubmissionModal += '<option value="DC">District Of Columbia</option>'            
ownerSubmissionModal += '<option value="FL">Florida</option>'            
ownerSubmissionModal += '<option value="GA">Georgia</option>'            
ownerSubmissionModal += '<option value="HI">Hawaii</option>'            
ownerSubmissionModal += '<option value="ID">Idaho</option>'            
ownerSubmissionModal += '<option value="IL">Illinois</option>'            
ownerSubmissionModal += '<option value="IN">Indiana</option>'            
ownerSubmissionModal += '<option value="IA">Iowa</option>'            
ownerSubmissionModal += '<option value="KS">Kansas</option>'            
ownerSubmissionModal += '<option value="KY">Kentucky</option>'            
ownerSubmissionModal += '<option value="LA">Louisiana</option>'            
ownerSubmissionModal += '<option value="ME">Maine</option>'            
ownerSubmissionModal += '<option value="MD">Maryland</option>'            
ownerSubmissionModal += '<option value="MA">Massachusetts</option>'            
ownerSubmissionModal += '<option value="MI">Michigan</option>'            
ownerSubmissionModal += '<option value="MN">Minnesota</option>'            
ownerSubmissionModal += '<option value="MS">Mississippi</option>'            
ownerSubmissionModal += '<option value="MO">Missouri</option>'            
ownerSubmissionModal += '<option value="MT">Montana</option>'            
ownerSubmissionModal += '<option value="NE">Nebraska</option>'            
ownerSubmissionModal += '<option value="NV">Nevada</option>'            
ownerSubmissionModal += '<option value="NH">New Hampshire</option>'            
ownerSubmissionModal += '<option value="NJ">New Jersey</option>'            
ownerSubmissionModal += '<option value="NM">New Mexico</option>'            
ownerSubmissionModal += '<option value="NY">New York</option>'            
ownerSubmissionModal += '<option value="NC">North Carolina</option>'            
ownerSubmissionModal += '<option value="ND">North Dakota</option>'            
ownerSubmissionModal += '<option value="OH">Ohio</option>'            
ownerSubmissionModal += '<option value="OK">Oklahoma</option>'            
ownerSubmissionModal += '<option value="OR">Oregon</option>'            
ownerSubmissionModal += '<option value="PA">Pennsylvania</option>'            
ownerSubmissionModal += '<option value="RI">Rhode Island</option>'            
ownerSubmissionModal += '<option value="SC">South Carolina</option>'            
ownerSubmissionModal += '<option value="SD">South Dakota</option>'            
ownerSubmissionModal += '<option value="TN">Tennessee</option>'            
ownerSubmissionModal += '<option value="TX">Texas</option>'            
ownerSubmissionModal += '<option value="UT">Utah</option>'            
ownerSubmissionModal += '<option value="VT">Vermont</option>'            
ownerSubmissionModal += '<option value="VA">Virginia</option>'            
ownerSubmissionModal += '<option value="WA">Washington</option>'            
ownerSubmissionModal += '<option value="WV">West Virginia</option>'            
ownerSubmissionModal += '<option value="WI">Wisconsin</option>'            
ownerSubmissionModal += '<option value="WY">Wyoming</option>'            
ownerSubmissionModal += '</select>'            
ownerSubmissionModal += '</div>'            
ownerSubmissionModal += '<div class="form-group col-md-2">'            
ownerSubmissionModal += '<label for="zip">Zip Code</label>'            
ownerSubmissionModal += '<input name="zip" type="text" class="form-control" id="zip" placeholder="Zip">'            
ownerSubmissionModal += '</div>'            
ownerSubmissionModal += '</div>'            
ownerSubmissionModal += '<div class="form-group">'            
ownerSubmissionModal += '<label for="policy">Policy</label>'            
ownerSubmissionModal += '<input name="policy" type="text" class="form-control" id="policy" placeholder="Enter Policy">'            
ownerSubmissionModal += '</div>'            
ownerSubmissionModal += '<div class="form-group">'            
ownerSubmissionModal += '<label for="expiration">Expiration Date</label>'            
ownerSubmissionModal += '<input name="expiration" type="text" class="form-control" id="expiration" placeholder="yyyy-dd-mm">'            
ownerSubmissionModal += '</div>'            
ownerSubmissionModal += '</div>'            
ownerSubmissionModal += '<div class="modal-footer">'            
ownerSubmissionModal += '<button id="submitOwner" type="submit" class="btn btn-success" name="save">Save</button>'            
ownerSubmissionModal += '<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>'            
ownerSubmissionModal += '</div>'            
ownerSubmissionModal += '</form>'            
ownerSubmissionModal += '</div>'            
ownerSubmissionModal += '</div>'            
ownerSubmissionModal += '</div>'          
ownerSubmissionModal += '</div>'

var ownerEditModal = '<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">'
ownerEditModal +='<div class="modal-dialog" role="document">'
ownerEditModal +='<div class="modal-content">'
ownerEditModal +='<div class="modal-header">'
ownerEditModal +='<h5 class="modal-title" id="editModalLabel"></h5>'
ownerEditModal +='<button type="button" class="close" data-dismiss="modal" aria-label="Close">'
ownerEditModal +='<span aria-hidden="true">&times;</span>'
ownerEditModal +='</button>'
ownerEditModal +='</div>'
ownerEditModal +='<div class="modal-body">'
ownerEditModal +='<form id="editOwnerForm" method="post">'
ownerEditModal +='<div class="form-group">'
ownerEditModal +='<input value="" name="id" type="hidden" class="form-control" id="editid">'
ownerEditModal +='<div class="form-row">'
ownerEditModal +='<div class="form-group col-md-6">'
ownerEditModal +='<label for="fname">First Name</label>'
ownerEditModal +='<input value="" name="fname" type="text" class="form-control" id="editfname">'
ownerEditModal +='</div>'
ownerEditModal +='<div class="form-group col-md-6">'
ownerEditModal +='<label for="lname">Last Name</label>'
ownerEditModal +='<input value="" name="lname" type="text" class="form-control" id="editlname">'
ownerEditModal +='</div>'
ownerEditModal +='</div>'
ownerEditModal +='<div class="form-group">'
ownerEditModal +='<label for="street1">Address Line 1</label>'
ownerEditModal +='<input value="" name="street1" type="text" class="form-control" id="editstreet1">'
ownerEditModal +='</div>'   
ownerEditModal +='<div class="form-group">'   
ownerEditModal +='<label for="street2">Address Line 2</label>'   
ownerEditModal +='<input value="" name="street2" type="text" class="form-control" id="editstreet2">'   
ownerEditModal +='</div>'   
ownerEditModal +='<div class="form-row">'   
ownerEditModal +='<div class="form-group col-md-6">'   
ownerEditModal +='<label for="city">City</label>'   
ownerEditModal +='<input value="" name="city" type="text" class="form-control" id="editcity">'   
ownerEditModal +='</div>'              
ownerEditModal +='<div class="form-group col-md-4">'              
ownerEditModal +='<label for="state">State</label>'              
ownerEditModal +='<select value="" name="state" class="form-control" id="editstate">'              
ownerEditModal += '<option value="AL">Alabama</option>'            
ownerEditModal += '<option value="AK">Alaska</option>'            
ownerEditModal += '<option value="AZ">Arizona</option>'            
ownerEditModal += '<option value="AR">Arkansas</option>'            
ownerEditModal += '<option value="CA">California</option>'            
ownerEditModal += '<option value="CO">Colorado</option>'            
ownerEditModal += '<option value="CT">Connecticut</option>'            
ownerEditModal += '<option value="DE">Delaware</option>'            
ownerEditModal += '<option value="DC">District Of Columbia</option>'            
ownerEditModal += '<option value="FL">Florida</option>'            
ownerEditModal += '<option value="GA">Georgia</option>'            
ownerEditModal += '<option value="HI">Hawaii</option>'            
ownerEditModal += '<option value="ID">Idaho</option>'            
ownerEditModal += '<option value="IL">Illinois</option>'            
ownerEditModal += '<option value="IN">Indiana</option>'            
ownerEditModal += '<option value="IA">Iowa</option>'            
ownerEditModal += '<option value="KS">Kansas</option>'            
ownerEditModal += '<option value="KY">Kentucky</option>'            
ownerEditModal += '<option value="LA">Louisiana</option>'            
ownerEditModal += '<option value="ME">Maine</option>'            
ownerEditModal += '<option value="MD">Maryland</option>'            
ownerEditModal += '<option value="MA">Massachusetts</option>'            
ownerEditModal += '<option value="MI">Michigan</option>'            
ownerEditModal += '<option value="MN">Minnesota</option>'            
ownerEditModal += '<option value="MS">Mississippi</option>'            
ownerEditModal += '<option value="MO">Missouri</option>'            
ownerEditModal += '<option value="MT">Montana</option>'            
ownerEditModal += '<option value="NE">Nebraska</option>'            
ownerEditModal += '<option value="NV">Nevada</option>'            
ownerEditModal += '<option value="NH">New Hampshire</option>'            
ownerEditModal += '<option value="NJ">New Jersey</option>'            
ownerEditModal += '<option value="NM">New Mexico</option>'            
ownerEditModal += '<option value="NY">New York</option>'            
ownerEditModal += '<option value="NC">North Carolina</option>'            
ownerEditModal += '<option value="ND">North Dakota</option>'            
ownerEditModal += '<option value="OH">Ohio</option>'            
ownerEditModal += '<option value="OK">Oklahoma</option>'            
ownerEditModal += '<option value="OR">Oregon</option>'            
ownerEditModal += '<option value="PA">Pennsylvania</option>'            
ownerEditModal += '<option value="RI">Rhode Island</option>'            
ownerEditModal += '<option value="SC">South Carolina</option>'            
ownerEditModal += '<option value="SD">South Dakota</option>'            
ownerEditModal += '<option value="TN">Tennessee</option>'            
ownerEditModal += '<option value="TX">Texas</option>'            
ownerEditModal += '<option value="UT">Utah</option>'            
ownerEditModal += '<option value="VT">Vermont</option>'            
ownerEditModal += '<option value="VA">Virginia</option>'            
ownerEditModal += '<option value="WA">Washington</option>'            
ownerEditModal += '<option value="WV">West Virginia</option>'            
ownerEditModal += '<option value="WI">Wisconsin</option>'            
ownerEditModal += '<option value="WY">Wyoming</option>'              
ownerEditModal +='</select>'              
ownerEditModal +='</div>'              
ownerEditModal +='<div class="form-group col-md-2">'              
ownerEditModal +='<label for="zip">Zip Code</label>'              
ownerEditModal +='<input value="" name="zip" type="text" class="form-control" id="editzip">'              
ownerEditModal +='</div>'              
ownerEditModal +='</div>'              
ownerEditModal +='<div class="form-group">'              
ownerEditModal +='<label for="policy">Policy</label>'              
ownerEditModal +='<input value="" name="policy" type="text" class="form-control" id="editpolicy">'              
ownerEditModal +='</div>'              
ownerEditModal +='<div class="form-group">'              
ownerEditModal +='<label for="expiration">Expiration Date</label>'              
ownerEditModal +='<input value="" name="expiration" type="text" class="form-control" id="editexpiration">'              
ownerEditModal +='</div>'              
ownerEditModal +='</div>'              
ownerEditModal +='<div class="modal-footer">'              
ownerEditModal +='<button id="updateOwner" type="submit" class="btn btn-success" name="updateOwner">Update</button>'              
ownerEditModal +='<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>'              
ownerEditModal +='</div>'              
ownerEditModal +='</form>'              
ownerEditModal +='</div>'              
ownerEditModal +='</div>'              
ownerEditModal +='</div>'              
ownerEditModal +='</div>'  


var itemModal = '<div class="modal fade" id="ownerItemsModal" tabindex="-1" role="dialog" aria-labelledby="ownersItemsModal" aria-hidden="true">'
itemModal += '<div class="modal-dialog modal-lg" role="document">'
itemModal += '<div class="modal-content">'
itemModal += '<div class="modal-header">'
itemModal += '<h5 class="modal-title" id="itemModalLabel"><strong></strong></h5>'
itemModal += '<button type="button" class="btn btn-success btn-sm mx-3" data-toggle="modal" data-target="#itemSubmissionModal">+</button>'
itemModal += '<button type="button" class="close" data-dismiss="modal" aria-label="Close">'
itemModal += '<span aria-hidden="true">&times;</span>'
itemModal += '</button>'
itemModal += '</div>'
itemModal += '<div class="modal-body">'
itemModal += '<table class="table table-responsive table-primary table-striped table-hover">'
itemModal += '<thead>'
itemModal += '<tr>'
itemModal += '<th>Item</th>'
itemModal += '<th>Description</th>'
itemModal += '<th>Valuation</th>'
itemModal += '<th>Method</th>'
itemModal += '<th nowrap>Creation Date</th>'
itemModal += '<th colspan=2>Action</th>'
itemModal += '</tr>'
itemModal += '</thead>'
itemModal += '<tbody id="itemBody">'            
itemModal += '</tbody>'        
itemModal += '</table> '        
itemModal += '</div>'        
itemModal += '</div>'        
itemModal += '</div>'        
itemModal += '</div>'

var itemSubmissionModal = '<div class="modal fade" id="itemSubmissionModal" tabindex="-1" role="dialog" aria-labelledby="itemSubmissionModalLabel" aria-hidden="true">'
itemSubmissionModal += '<div class="modal-dialog" role="document">'
itemSubmissionModal += '<div class="modal-content">'
itemSubmissionModal += '<div class="modal-header">'
itemSubmissionModal += '<h5 class="modal-title" id="itemSubmissionModalLabel"><strong>Add a New Item</strong></h5>'
itemSubmissionModal += '<button type="button" class="close" data-dismiss="modal" aria-label="Close">'
itemSubmissionModal += '<span aria-hidden="true">&times;</span>'
itemSubmissionModal += '</button>'
itemSubmissionModal += '</div>'
itemSubmissionModal += '<div class="modal-body">'
itemSubmissionModal += '<form id="createItemForm" method="post">'
itemSubmissionModal += '<div class="form-group">'
itemSubmissionModal += '<label for="name">Item Name</label>'
itemSubmissionModal += '<input name="name" type="text" class="form-control" id="itemName" placeholder="Enter Name of Item">'
itemSubmissionModal += '</div>'
itemSubmissionModal += '<div class="form-group">'
itemSubmissionModal += '<label for="photo">Photo</label>'
itemSubmissionModal += ' <input name="photo" type="text" class="form-control" id="itemPhoto" placeholder="Enter Link to Photo if Avaliable">'
itemSubmissionModal += '</div>'
itemSubmissionModal += '<div class="form-group">'
itemSubmissionModal += '<div class="form-group">'
itemSubmissionModal += '<label for="description">Description</label>'
itemSubmissionModal += '<textarea name="description" class="form-control" id="itemDescription" rows="3" placeholder="Write Description of Item Here"></textarea>'
itemSubmissionModal += '</div>'
itemSubmissionModal += '<div class="form-row">'
itemSubmissionModal += '<div class="form-group col-md-6">'
itemSubmissionModal += '<label for="valuation">Valuation Amount</label>'
itemSubmissionModal += '<input name="valuation" type="text" class="form-control" id="itemValuation" placeholder="Enter Items Valuation Amount">'
itemSubmissionModal += '</div>'
itemSubmissionModal += '<div class="form-group col-md-6">'
itemSubmissionModal += '<label for="method">Method</label>'
itemSubmissionModal += '<input name="method" type="text" class="form-control" id="itemMethod" placeholder="Enter Method of Valuation">'
itemSubmissionModal += '</div>'
itemSubmissionModal += '</div>'
itemSubmissionModal += '<p>Verified</p>'
itemSubmissionModal += '<div class="form-check">'
itemSubmissionModal += '<input class="form-check-input" type="radio" name="verified" id="itemverified" value=1>'
itemSubmissionModal += '<label class="form-check-label" for="exampleRadios1">'
itemSubmissionModal += 'Yes'
itemSubmissionModal += '</label>'
itemSubmissionModal += '</div>'
itemSubmissionModal += '<div class="form-check">'
itemSubmissionModal += '<input class="form-check-input" type="radio" name="verified" id="itemverified" value=0 checked>'
itemSubmissionModal += '<label class="form-check-label" for="exampleRadios2">'
itemSubmissionModal += 'No'
itemSubmissionModal += '</label>'
itemSubmissionModal += '</div>'
itemSubmissionModal += '<br>'
itemSubmissionModal += '<div class="form-group">'
itemSubmissionModal += '<label for="creationDate">Creation Date</label>'
itemSubmissionModal += '<input name="creationDate" type="text" class="form-control" id="itemDate" placeholder="yyyy-dd-mm">'
itemSubmissionModal += '</div>'
itemSubmissionModal += '</div>'
itemSubmissionModal += '<div class="modal-footer">'
itemSubmissionModal += '<button id="submitItem" type="button" class="btn btn-success" name="saveItem">Save</button>'
itemSubmissionModal += '<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>'
itemSubmissionModal += '</div>'
itemSubmissionModal += '</form>'
itemSubmissionModal += '</div>'
itemSubmissionModal += '</div>'
itemSubmissionModal += '</div>'
itemSubmissionModal += '</div>'


var itemEditModal = '<div class="modal fade" id="itemEditModal" tabindex="-1" role="dialog" aria-labelledby="itemEditModalLabel" aria-hidden="true">'
itemEditModal += '<div class="modal-dialog" role="document">'
itemEditModal += '<div class="modal-content">'
itemEditModal += '<div class="modal-header">'
itemEditModal += '<h5 class="modal-title" id="itemEditModalLabel"><strong></strong></h5>'
itemEditModal += '<button type="button" class="close" data-dismiss="modal" aria-label="Close">'
itemEditModal += '<span aria-hidden="true">&times;</span>'
itemEditModal += '</button>'
itemEditModal += '</div>'
itemEditModal += '<div class="modal-body">'
itemEditModal += '<div class="modal-body">'
itemEditModal += '<form id="editItemForm" method="post">'
itemEditModal += '<div class="form-group">'
itemEditModal += '<input value="" name="id" type="hidden" class="form-control" id="editItemId">'
itemEditModal += '<label for="name">Item Name</label>'
itemEditModal += '<input name="name" type="text" class="form-control" id="editName" placeholder="Enter Name of Item">'
itemEditModal += '</div>'
itemEditModal += '<div class="form-group">'
itemEditModal += '<label for="photo">Photo</label>'
itemEditModal += ' <input name="photo" type="text" class="form-control" id="editPhoto" placeholder="Enter Link to Photo if Avaliable">'
itemEditModal += '</div>'
itemEditModal += '<div class="form-group">'
itemEditModal += '<div class="form-group">'
itemEditModal += '<label for="description">Description</label>'
itemEditModal += '<textarea name="description" class="form-control" id="editDescription" rows="3" placeholder="Write Description of Item Here"></textarea>'
itemEditModal += '</div>'
itemEditModal += '<div class="form-row">'
itemEditModal += '<div class="form-group col-md-6">'
itemEditModal += '<label for="valuation">Valuation Amount</label>'
itemEditModal += '<input name="valuation" type="text" class="form-control" id="editValuation" placeholder="Enter Items Valuation Amount">'
itemEditModal += '</div>'
itemEditModal += '<div class="form-group col-md-6">'
itemEditModal += '<label for="method">Method</label>'
itemEditModal += '<input name="method" type="text" class="form-control" id="editMethod" placeholder="Enter Method of Valuation">'
itemEditModal += '</div>'
itemEditModal += '</div>'
itemEditModal += '<p>Verified</p>'
itemEditModal += '<div class="form-check">'
itemEditModal += '<input class="form-check-input" type="radio" name="verified" id="editVerified" value=1>'
itemEditModal += '<label class="form-check-label" for="exampleRadios1">'
itemEditModal += 'Yes'
itemEditModal += '</label>'
itemEditModal += '</div>'
itemEditModal += '<div class="form-check">'
itemEditModal += '<input class="form-check-input" type="radio" name="verified" id="editVerified" value=0 checked>'
itemEditModal += '<label class="form-check-label" for="exampleRadios2">'
itemEditModal += 'No'
itemEditModal += '</label>'
itemEditModal += '</div>'
itemEditModal += '<br>'
itemEditModal += '<div class="form-group">'
itemEditModal += '<label for="creationDate">Creation Date</label>'
itemEditModal += '<input id"editCreationDate" name="creationDate" type="text" class="form-control" placeholder="yyyy-dd-mm">'
itemEditModal += '</div>'
itemEditModal += '</div>'
itemEditModal += '<div class="modal-footer">'
itemEditModal += '<button id="updateItem" type="button" class="btn btn-success" name="saveItem">Save</button>'
itemEditModal += '<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>'
itemEditModal += '</div>'
itemEditModal += '</form>'
itemEditModal += '</div>'
itemEditModal += '</div>'
itemEditModal += '</div>'
itemEditModal += '</div>'

 
            
        
            
            
        
        
    
        
    
